pipeline:
  build:
    image: node
    commands:
      - npm ci
      - npm run lint
      - npm run test
      - npm run build
  release:
    when:
      event: tag
    image: plugins/npm
    username: flowup
    email: hello@flowup.cz
    secrets: [npm_password]
